# Where your public ssh key that is registered on Github is. By default it
# looks in your ssh folder for a file called `id_rsa`
# PublicKeyPath = ~/.ssh/id_rsa

# Zappr Config
[zappr]
    # Defines the url for Zappr. Comment it out to load it from ZAPPR_URL environment variable
    URL="https://zappr.domain.com"

    # Specifies if calls made by Zappr to Github should use its own Client token or yours. Comment it out to load it from ZAPPR_USE_APP_CREDENTIALS environment variable
    UseZapprGithubCredentials="true"

[github]
    # Defines the github organization
    Organization="hellofresh"

    # Defines the github token
    # Create a new one here: https://github.com/settings/tokens/new with `repo` access
    Token=""

    # Defines permission specifies the permission to grant the team on this repository.
  	# Possible values are:
  	#     pull - team members can pull, but not push to or administer this repository
  	#     push - team members can pull and push, but not administer this repository
  	#     admin - team members can pull, push and administer this repository

    # To get a team ID: curl -s -i -X GET -u TOKEN:x-oauth-basic -d '' https://api.github.com/orgs/hellofresh/teams | grep -A1 "TEAM_NAME"
    Teams=[
        #Example
        {ID=1234, Permission='pull'},
    ]

    # Defines permission specifies the permission to grant the user on this repository.
    Collaborators=[
        #Example
        {Username="example", Permission='push'},
    ]

    # Adds a set of labels when creating the repo
    Labels=[
        {Name="Please CR", Color="c2e0c6"},
        {Name="Do not merge", Color="b60205"},
    ]

    # Removes the default github's labels
    RemoveDefaultLabels=true

    # Defines webhooks that will be added
    Webhooks=[
        {Type="web", Config={url="http://example.com/webhook", content_type="json"}}
    ]

    # Defines branch protections
    Protections={master=["zappr"]}

[githubtestorg]
    # Defines the github test organization
    Organization="yourOrg"

    # Defines the github test token
    Token=""
