# Defines the application log level
LogLevel="debug"

# Where your public ssh key that is registered on Github is. By default it 
# looks in your ssh folder for a file called `id_rsa`
# PublicKeyPath = ~/.ssh/id_rsa

[pullapprove]
    # Defines the pull approve organization
    Token=""
    # Defines the pull approve filename
    filename="./.pullapprove.yml"
    # Defines the pull approve branch
    protectedBranchName="master"

[github]
    # Defines the github organization
    Organization="yourOrg"

    # Defines the github token
    Token=""

    # Defines permission specifies the permission to grant the user on this repository.
	# Possible values are:
	#     pull - team members can pull, but not push to or administer this repository
	#     push - team members can pull and push, but not administer this repository
	#     admin - team members can pull, push and administer this repository
    Teams=[
        #Example
        {ID=1234, Permission='pull'},
    ]

    # Adds a set of labels when creating the repo
    Labels=[
        {Name='custom', Color='ad974f'}, 
    ]

    # Removes the default github's labels
    RemoveDefaultLabels=true

    # Defines webhooks that will be added
    Webhooks=[
        {Type="web", Config={url="http://example.com/webhook", content_type="json"}}
    ]

    # Defines branch protections
    Protections={master=["code-review/pullapprove"]}
