project_name: kangal

builds:
  - id: binary-build
    main: main.go
    binary: github-cli
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
